

import localFont from 'next/font/local'
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const montserrat = localFont({
  src: "../../public/fonts/Montserrat-VariableFont_wght.woff2",
  display: 'swap',
  variable: "--font-montserrat"
});

const nunito = localFont({
  src: "../../public/fonts/Nunito-VariableFont_wght.woff2",
  display: 'swap',
  variable: "--font-nunito"
});

export const metadata = {
  title: "Venki Musti | Best Numerologist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${nunito.variable} font-montserrat`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
